name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Dar permissão ao Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Rodar testes Cypress
        run: npx cypress run